name: ShopkeeperCopy
version: '${project.version}'
description: Copy admin shopkeepers via command
authors: [blablubbabc]
softdepend: [Shopkeepers]

main: de.blablubbabc.shopkeepercopy.ShopkeeperCopyPlugin

commands:
    sk-copy:
        description: Copy an admin shopkeeper.
        aliases: [skcopy, shopkeeper-copy, shopkeepers-copy]
        usage: '/<command> <shop-id> <world> <x> <y> <z>'

permissions:
    shopkeepercopy.copy:
        description: Copy admin shopkeepers.
        default: op
